/** @type {import('tailwindcss').Config} */
export default {
  content: [],
  theme: {
    colors: {
      white: '#FFFFFF',
      black: '#000000',
      primary: {
        0: 'rgba(var(--sys-color-primary-0))',
        10: 'rgba(var(--sys-color-primary-10))',
        20: 'rgba(var(--sys-color-primary-20))',
        30: 'rgba(var(--sys-color-primary-30))',
        40: 'rgba(var(--sys-color-primary-40))',
        50: 'rgba(var(--sys-color-primary-50))',
        60: 'rgba(var(--sys-color-primary-60))',
        70: 'rgba(var(--sys-color-primary-70))',
        80: 'rgba(var(--sys-color-primary-80))',
        90: 'rgba(var(--sys-color-primary-90))',
        95: 'rgba(var(--sys-color-primary-95))',
        99: 'rgba(var(--sys-color-primary-99))',
        100: 'rgba(var(--sys-color-primary-100))',
        DEFAULT: 'rgba(var(--sys-color-primary))',
        on: 'rgba(var(--sys-color-on-primary))',
        container: 'rgba(var(--sys-color-primary-container))',
        'on-container': 'rgba(var(--sys-color-on-primary-container))',
      },
      secondary: {
        0: 'rgba(var(--sys-color-secondary-0))',
        10: 'rgba(var(--sys-color-secondary-10))',
        20: 'rgba(var(--sys-color-secondary-20))',
        30: 'rgba(var(--sys-color-secondary-30))',
        40: 'rgba(var(--sys-color-secondary-40))',
        50: 'rgba(var(--sys-color-secondary-50))',
        60: 'rgba(var(--sys-color-secondary-60))',
        70: 'rgba(var(--sys-color-secondary-70))',
        80: 'rgba(var(--sys-color-secondary-80))',
        90: 'rgba(var(--sys-color-secondary-90))',
        95: 'rgba(var(--sys-color-secondary-95))',
        99: 'rgba(var(--sys-color-secondary-99))',
        100: 'rgba(var(--sys-color-secondary-100))',
        DEFAULT: 'rgba(var(--sys-color-secondary))',
        on: 'rgba(var(--sys-color-on-secondary))',
        container: 'rgba(var(--sys-color-secondary-container))',
        'on-container': 'rgba(var(--sys-color-on-secondary-container))',
      },
      tertiary: {
        0: 'rgba(var(--sys-color-tertiary-0))',
        10: 'rgba(var(--sys-color-tertiary-10))',
        20: 'rgba(var(--sys-color-tertiary-20))',
        30: 'rgba(var(--sys-color-tertiary-30))',
        40: 'rgba(var(--sys-color-tertiary-40))',
        50: 'rgba(var(--sys-color-tertiary-50))',
        60: 'rgba(var(--sys-color-tertiary-60))',
        70: 'rgba(var(--sys-color-tertiary-70))',
        80: 'rgba(var(--sys-color-tertiary-80))',
        90: 'rgba(var(--sys-color-tertiary-90))',
        95: 'rgba(var(--sys-color-tertiary-95))',
        99: 'rgba(var(--sys-color-tertiary-99))',
        100: 'rgba(var(--sys-color-tertiary-100))',
        DEFAULT: 'rgba(var(--sys-color-tertiary))',
        on: 'rgba(var(--sys-color-on-tertiary))',
        container: 'rgba(var(--sys-color-tertiary-container))',
        'on-container': 'rgba(var(--sys-color-on-tertiary-container))',
      },
      error: {
        0: 'rgba(var(--sys-color-error-0))',
        10: 'rgba(var(--sys-color-error-10))',
        20: 'rgba(var(--sys-color-error-20))',
        30: 'rgba(var(--sys-color-error-30))',
        40: 'rgba(var(--sys-color-error-40))',
        50: 'rgba(var(--sys-color-error-50))',
        60: 'rgba(var(--sys-color-error-60))',
        70: 'rgba(var(--sys-color-error-70))',
        80: 'rgba(var(--sys-color-error-80))',
        90: 'rgba(var(--sys-color-error-90))',
        95: 'rgba(var(--sys-color-error-95))',
        99: 'rgba(var(--sys-color-error-99))',
        100: 'rgba(var(--sys-color-error-100))',
        DEFAULT: 'rgba(var(--sys-color-error))',
        on: 'rgba(var(--sys-color-on-error))',
        container: 'rgba(var(--sys-color-error-container))',
        'on-container': 'rgba(var(--sys-color-on-error-container))',
      },
      success: {
        0: 'rgba(var(--sys-color-success-0))',
        10: 'rgba(var(--sys-color-success-10))',
        20: 'rgba(var(--sys-color-success-20))',
        30: 'rgba(var(--sys-color-success-30))',
        40: 'rgba(var(--sys-color-success-40))',
        50: 'rgba(var(--sys-color-success-50))',
        60: 'rgba(var(--sys-color-success-60))',
        70: 'rgba(var(--sys-color-success-70))',
        80: 'rgba(var(--sys-color-success-80))',
        90: 'rgba(var(--sys-color-success-90))',
        95: 'rgba(var(--sys-color-success-95))',
        99: 'rgba(var(--sys-color-success-99))',
        100: 'rgba(var(--sys-color-success-100))',
        DEFAULT: 'rgba(var(--sys-color-success))',
        on: 'rgba(var(--sys-color-on-success))',
        container: 'rgba(var(--sys-color-success-container))',
        'on-container': 'rgba(var(--sys-color-on-success-container))',
      },
      neutral: {
        0: 'rgba(var(--sys-color-neutral-0))',
        10: 'rgba(var(--sys-color-neutral-10))',
        20: 'rgba(var(--sys-color-neutral-20))',
        30: 'rgba(var(--sys-color-neutral-30))',
        40: 'rgba(var(--sys-color-neutral-40))',
        50: 'rgba(var(--sys-color-neutral-50))',
        60: 'rgba(var(--sys-color-neutral-60))',
        70: 'rgba(var(--sys-color-neutral-70))',
        80: 'rgba(var(--sys-color-neutral-80))',
        90: 'rgba(var(--sys-color-neutral-90))',
        95: 'rgba(var(--sys-color-neutral-95))',
        99: 'rgba(var(--sys-color-neutral-99))',
        100: 'rgba(var(--sys-color-neutral-100))',
      },
      'neutral-variant': {
        0: 'rgba(var(--sys-color-neutral-variant-0))',
        10: 'rgba(var(--sys-color-neutral-variant-10))',
        20: 'rgba(var(--sys-color-neutral-variant-20))',
        30: 'rgba(var(--sys-color-neutral-variant-30))',
        40: 'rgba(var(--sys-color-neutral-variant-40))',
        50: 'rgba(var(--sys-color-neutral-variant-50))',
        60: 'rgba(var(--sys-color-neutral-variant-60))',
        70: 'rgba(var(--sys-color-neutral-variant-70))',
        80: 'rgba(var(--sys-color-neutral-variant-80))',
        90: 'rgba(var(--sys-color-neutral-variant-90))',
        95: 'rgba(var(--sys-color-neutral-variant-95))',
        99: 'rgba(var(--sys-color-neutral-variant-99))',
        100: 'rgba(var(--sys-color-neutral-variant-100))',
      },
      surface: {
        dim: 'rgba(var(--light-surface-dim))',
        DEFAULT: 'rgba(var(--light-surface))',
        bright: 'rgba(var(--light-surface-bright))',
        'container-lowest': 'rgba(var(--light-surface-container-lowest))',
        'container-low': 'rgba(var(--light-surface-container-low))',
        container: 'rgba(var(--light-surface-container))',
        'container-high': 'rgba(var(--light-surface-container-high))',
        'container-highest': 'rgba(var(--light-surface-container-highest))',
        on: 'rgba(var(--sys-color-on-surface))',
        'on-variant': 'rgba(var(--sys-color-on-surface-variant))',
      },
      inverse: {
        surface: 'rgba(var(--sys-color-inverse-surface))',
        'on-surface': 'rgba(var(--sys-color-inverse-on-surface))',
        primary: 'rgba(var(--sys-color-inverse-primary))',
      },
      outline: {
        DEFAULT: 'rgba(var(--sys-color-outline))',
        variant: 'rgba(var(--sys-color-outline-variant))',
      },
    },
    fontSize: {
      'display-l': ['3.625rem', '4rem'],
      'display-m': ['2.875rem', '3.25rem'],
      'display-s': ['2.25rem', '2.75rem'],
      'headline-l': ['2rem', '3rem'],
      'headline-m': ['1.75rem', '2.25rem'],
      'headline-s': ['1.5rem', '2rem'],
      'title-l': ['1.375rem', '1.75rem'],
      'title-m': ['1rem', '1.5rem'],
      'title-s': ['0.875rem', '1.25rem'],
      label: ['0.875rem', '1.1875rem'],
      placeholder: ['1rem', '1.5rem'],
      'button-l': ['1.125rem', '1.5rem'],
      'button-m': ['1rem', '1.375rem'],
      'button-s': ['0.9375rem', '1.25rem'],
      'content-l': ['1.125rem', '1.75rem'],
      'content-m': ['0.875rem', '1.25rem'],
      'content-s': ['0.75rem', '1rem'],
    },
    boxShadow: {
      none: '0 0 transparent',
      card: '0 0 12px 0 rgba(0, 0, 0, 0.1)',
      'button-hover': '0 0 6px 0 rgba(0, 0, 0, 0.2)',
      'input-focused': '0 0 10px 0 rgba(var(--sys-color-primary-40), 0.2)',
      // TODO: 暫時命名為 header，目前只使用在 header 上
      header: '0 2px 10px 0 rgba(0, 0, 0, 0.16)',
      // TODO: 暫時命名為 member，目前只使用在 member 上
      member: '0 2px 20px 0 rgba(0, 0, 0, 0.16)',
    },
  },
  plugins: [],
};
