import { ApiPathImgur } from '../constants/api/imgur-api.const';
import type {
  GetImageResponse,
  PostImageResponse,
} from '../models/api/imgur.model';

interface DataFormatMap {
  [ApiPathImgur.GetImage]: GetImageResponse;
  [ApiPathImgur.PostImage]: PostImageResponse;
}

export const IMGUR_MOCK: DataFormatMap = {
  [ApiPathImgur.GetImage]: {
    data: {
      id: '7AqmOHl',
      title: 'Simple upload',
      description: 'This is a simple image upload in Imgur',
      datetime: 1717508690,
      type: 'image/png',
      animated: false,
      width: 542,
      height: 960,
      size: 196574,
      views: 0,
      bandwidth: 0,
      vote: null,
      favorite: false,
      nsfw: false,
      section: null,
      account_url: null,
      account_id: 107618633,
      is_ad: false,
      in_most_viral: false,
      has_sound: false,
      tags: [],
      ad_type: 0,
      ad_url: '',
      edited: '0',
      in_gallery: false,
      deletehash: 'RDeBujLALKyh8Kl',
      name: '',
      link: 'https://i.imgur.com/7AqmOHl.png',
      ad_config: {
        safeFlags: ['not_in_gallery', 'share'],
        highRiskFlags: [],
        unsafeFlags: [],
        wallUnsafeFlags: [],
        showsAds: true,
        showAdLevel: 2,
        safe_flags: ['not_in_gallery', 'share'],
        high_risk_flags: [],
        unsafe_flags: [],
        wall_unsafe_flags: [],
        show_ads: true,
        show_ad_level: 2,
        nsfw_score: 0,
      },
    },
    success: true,
    status: 200,
  },
  [ApiPathImgur.PostImage]: {
    status: 200,
    success: true,
    data: {
      id: '7AqmOHl',
      deletehash: 'RDeBujLALKyh8Kl',
      account_id: 107618633,
      account_url: 'hou1131',
      ad_type: null,
      ad_url: null,
      title: 'Simple upload',
      description: 'This is a simple image upload in Imgur',
      name: '',
      type: 'image/png',
      width: 542,
      height: 960,
      size: 196574,
      views: 0,
      section: null,
      vote: null,
      bandwidth: 0,
      animated: false,
      favorite: false,
      in_gallery: false,
      in_most_viral: false,
      has_sound: false,
      is_ad: false,
      nsfw: null,
      link: 'https://i.imgur.com/7AqmOHl.png',
      tags: [],
      datetime: 1717508690,
      mp4: '',
      hls: '',
    },
  },
};
